### ISSUE TITLE
Is it possible to support skeletal animation tools like Spine?

### ISSUE THREAD

**Issue by coolzilj** [luanpotter/flame#10]

**Comment by luanpotter** [comment]
Not currently.

Is [this](http://esotericsoftware.com/) the Spine you are referring to? I'm unfamiliar with it, could you elaborate on that?

From what I've gathered, sadly it's a proprietary and paid software, so I don't know how we could integrate with it. From what I quickly saw at their website, they allow to create more natural feeling animations that would take an inordinate amount of frames to do with simple sprite sheets; is there an open format or specification to define this, so that we can support it? If you like, you can contribute with a PR :)

**Comment by coolzilj** [comment]
Thx for the quick response, yes, we're talking the same Spine.

Actually the Spine [runtimes](http://esotericsoftware.com/spine-runtimes) are all open sources, including the official ones, except the Spine Editor(Paid), so specification is not hard to find(I supposed, actually this is my first time to work with it).

I found two dart runtimes but all based on html/webgl, [StageXL_Spine(based on StageXL engine)](https://github.com/bp74/StageXL_Spine), [FedeOmoto/spine](https://github.com/FedeOmoto/spine). 

I'm digging the sources, trying to find a clue.

**Comment by luanpotter** [comment]
I see, it looks like there is plenty of documentation and open implementations for several languages, including Dart for web, which would make it very feasible to understand and implement this inside flame.

It would be a great addition to the platform, but also a monumental work, for which I sadly don't quite have the time right now. If you want to help creating this binding, please feel free, and I can provide all assistance related to Flame. Otherwise, I'll have that as one of our goals for a future time. Thanks for you suggestion!

**Comment by coolzilj** [comment]
Sure thing, I'd like to help.
