### ISSUE TITLE
Saving game state

### ISSUE THREAD

**Issue by aleslanik2** [luanpotter/flame#18]
Hi, i am begining developing simple game in flame. And i have no idea how to save game state in situation when  application goes to background. 
In current state, after moving back to foreground, is the game restarted. 

Thank you for your reply and have a nice day

PS. Sorry for my English, my language skill is very poor :-)

**Comment by erickzanardo** [comment]
Hello @aleslanik2 I don't if I quite understand what you are asking, but when the app is moved to background, it is not killed (at least on Android, I'm not sure about iOs) you could keep your state on memory and use the lifecycleStateChange method to resume the game from your state.

Another option is to save your state on the shared preferences of the device, flame doesn't provide any solution for this out of the box, but I can recommend [this lib](https://pub.dartlang.org/packages/shared_preferences) in order to achieve that.

Hope this helped, any other question, feel free to ask

**Comment by luanpotter** [comment]
Perfectly put, @erickzanardo, thanks! I'm closing this issue, but please feel free to open new ones if necessary :)
