### ISSUE TITLE
Does flame support large size images?

### ISSUE THREAD

**Issue by wonsuyon** [luanpotter/flame#26]
I tested 3000px x 4000px 1MB png x 100 files in /assets/images.
and

void main() async {
    ....
    await Flame.images.loadAll(list);
}

40 images loaded but over 50 failed out of memory. (3g ram device)
android:largeHeap="true" didn't help.

Do you have any solutions?

(actually i need 1MB x 500 images..)

**Comment by luanpotter** [comment]
I agree with @datayeah , maybe you should consider splitting your sprite sheet into several bits? Then you can load one bit per level, that is, I'm assuming you don't use the entirety of your enormous sprite sheets at the same time!

Or, you could compress your image, using jpg or some sort of loss-y compression algorithm. 

Otherwise, there is simply no solution; you could load all sprites on demand, but your game would be slow as heck, because you'd need to reload files from the disk every render tick. 3 GB ram devices are pretty standard, AFAICT, so I would definitely not recommend this last approach. But the first two seem pretty viable.

**Comment by wonsuyon** [comment]
Thank you.
The tinyPNG helps and the Flame works fine with no delay for the 40MB loading.
But at this moment i need Unity instead..

**Comment by luanpotter** [comment]
I'm glad it worked out! If there is any feature missing from flame that you'd like to use, please feel free to open an issue or even contribute with a PR! It'd be really neat if we provided everything you need. Best regards!
