### ISSUE TITLE
Game as Widget - Improvements

### ISSUE THREAD

**Issue by luanpotter** [luanpotter/flame#54]
There are a couple of things that requires doing because of #50. These are important things to fix, so I'm adding here for us not to forget!

* Fix all examples, docs and guides to use the new, non-deprecated syntax.
* Fix the following problem: now that Game is itself a stateless widget, if cannot have non final (changing) variables. However, a game instance should be able to add non final references as desired. In fact, base game has many, and its giving the following warning:

> This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts

Other stuff added by the user will give the same problem. So, we need to find a way to fix this ASAP.

**Comment by luanpotter** [comment]
Currently we have all these warnings that need to be fixed:

```
Analyzing flame...
  hint • 'widget' is deprecated and shouldn't be used at doc/examples/aseprite/lib/main.dart:7:36 • deprecated_member_use
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at doc/examples/aseprite/lib/main.dart:9:7 • must_be_immutable
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at doc/examples/text/lib/main.dart:33:7 • must_be_immutable
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at doc/examples/tiled/lib/main.dart:10:7 • must_be_immutable
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at example/lib/main.dart:48:7 • must_be_immutable
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at lib/game.dart:167:16 • must_be_immutable
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at lib/game.dart:308:7 • must_be_immutable
  hint • 'widget' is deprecated and shouldn't be used at lib/game.dart:358:19 • deprecated_member_use_from_same_package
  hint • 'widget' is deprecated and shouldn't be used at lib/game.dart:361:19 • deprecated_member_use_from_same_package
  hint • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BaseGame.components, BaseGame._addLater, BaseGame.size, BaseGame.camera, BaseGame._dts at test/resizable_test.dart:19:7 • must_be_immutable
10 hints found.
```

**Comment by feroult** [comment]
@Luan what do you think about making those classes immutable?

**Comment by luanpotter** [comment]
I think the classes that extend Game cannot be forced to be immutable, because every game is going to want to add stuff to their game class that are not necessarily final. I think our implementation must have a way to take care of that in a way that flutter is happy with in the end and doesn't give the warnings. Maybe convert to a final wrapper or something...

**Comment by feroult** [comment]
I couldn't find any  solution, since all Widget hierarchy is `@immutable`.

It is a Flutter patter to make Widgets, even the `StatefulWidget` immutable. Users should have some `final state`-ish design in their classes to control their state. 

Don't know, if we decide that a Game to be mutable and allow non-final members I seems its better to keep the current API.

**Comment by feroult** [comment]
Correcting myself. 

`StatefullWidgets` have a `State`. This state can have non-final members... That what we should have two classes also... Don't know if it is easy to understand.

**Comment by erickzanardo** [comment]
@feroult you mean we should add the game instance on the Widget state?

**Comment by erickzanardo** [comment]
We also need to change here: https://github.com/luanpotter/flame#game-loop

**Comment by feroult** [comment]
Yeah something like this. I mean.... Flutter has a `StatefullWidget` which is `@immutable` and a seperated `State` object, which is _not_ `@immutable`.

We need to have something similar to allow `non-final` members in `Game`. 

It seems harder than what we have with `.widget` API.

**Comment by renancaraujo** [comment]
@feroult @erickzanardo @luanpotter 
Stateless and Stateful widgets are ideal for composing. I mean, there is two kinds of Widgets:

### Second type: the ones who paints stuff ([RenderWidgets](https://docs.flutter.io/flutter/widgets/RenderObjectWidget-class.html))
Those widgets are generally responsible for having its own rendering characterists, like Columns that puts children on a vertical ordenation, Container, etc.
Those widgets can hold none ([leaf](https://docs.flutter.io/flutter/widgets/LeafRenderObjectWidget-class.html)), one ([singlechild](https://docs.flutter.io/flutter/widgets/SingleChildRenderObjectWidget-class.html)) and maybe [several](https://docs.flutter.io/flutter/widgets/MultiChildRenderObjectWidget-class.html) children. 

### Second type: the ones where composed layouts
the ones that most of us create on a normal flutter applications, generally extending `Stateless` and `Stateful` widgets. This is ideal for cases where the widget paint nothing per se, but is composed 

### Conclusion
Since a Flame game takes care of its own rendering process, I  would chose it to be a RenderObjectWidget, more specifically, a [LeafRenderObjectWidget](https://docs.flutter.io/flutter/widgets/LeafRenderObjectWidget-class.html).

(There is some other types like [ProxyWidgets](https://docs.flutter.io/flutter/widgets/ProxyWidget-class.html) but lets ignore them for now)

**Comment by renancaraujo** [comment]
[For example, Flare-flutter uses LeafRenderObjectWidget.](https://github.com/2d-inc/Flare-Flutter/blob/master/flare_flutter/lib/flare_actor.dart)

**Comment by feroult** [comment]
`abstract class LeafRenderObjectWidget extends RenderObjectWidget`
`abstract class RenderObjectWidget extends Widget`

All that comes from `Widget` still `@immutable`

**Comment by renancaraujo** [comment]
Why  Game has to be an Widget?

**Comment by erickzanardo** [comment]
This has been resolved by [this commit](https://github.com/luanpotter/flame/commit/502b74e939271d647cc3af8e4f0230a1a573083c) right?

**Comment by feroult** [comment]
Yes... For now, this is a rollback. We're going to discuss this again someday soon :)

**Comment by erickzanardo** [comment]
Sure, but we should close this right? Since this are because of problems that does not happen anymore since the rollback

**Comment by renancaraujo** [comment]
There are some errors on master after that commit: #59

**Comment by erickzanardo** [comment]
Thanks @renancaraujo, already merged
