### ISSUE TITLE
Creating animationAsWidget in moving widget places animation in wrong position

### ISSUE THREAD

**Issue by BSChuang** [luanpotter/flame#56]
I'm not sure if I'm doing something wrong, but whenever I place a widget created with Flame.util.animationAsWidget in a moving Widget such as a GridView or ListView, the animations are in the completely wrong position. For example, the skeleton sprite should be within the green container, but it is not at all. There is no problem with placing the animationAsWidgets in rows or columns, only when in moving components.
![image](https://user-images.githubusercontent.com/22308706/54174093-28e01e80-445b-11e9-8e1d-c2338bde7eb3.png)

**Comment by luanpotter** [comment]
Hi, @BSChuang , thanks a lot for reporting this issue!

That is indeed a bug because I have not considered this possibility of moving widgets on the implementation of EmbeddedGame. The fix should relatively simple, we need to update the viewport position for the game whenever the parent changes us.

I can take a look at this later to fix, or, if you ware interested, you can contribute with a PR!

Thanks again for the report :)

**Comment by renancaraujo** [comment]
Just opened a PR addressing this problem: #63

**Comment by renancaraujo** [comment]
@BSChuang Since this problem has been tackled in #63, which was merged and released on 0.10.3, I will close this issue now. If you still face this problem or think it was not saved properly, consider reopening it and let's keep discussing.
