### ISSUE TITLE
Does not compile anymore 

### ISSUE THREAD

**Issue by oth-aw** [luanpotter/flame#74]
Suddenly this error occurs:

`Compiler message:
file:///Users/XXXX/.pub-cache/hosted/pub.dartlang.org/flame-0.10.3/lib/svg.dart:26:17: Error: Too few positional arguments: 3 required, 2 given.
    svgRoot.draw(canvas, null);`
Reason is in file lib/src/vector_drawable.dart from [flutter_svg](https://github.com/dnfield/flutter_svg/commit/60b66967d09d850569ecfe6df5b3d31709d78b30)
`void draw(Canvas canvas, ColorFilter colorFilter);`
was changed to
`void draw(Canvas canvas, ColorFilter colorFilter, Rect bounds);`

**Comment by erickzanardo** [comment]
Hey @oth-aw thanks for reporting this, yes that is the reason, there was a breaking change on this package from the version we used, and the latest version, and since we did not locked the patch version of flutter_svg on flame pubspec, flame is breaking.

We will resolve this for the next version. In the meantime, as a workaround, you can change your pubspec.lock and set the flutter_svg version to 0.12.0, this should solve your problem for now until we release the next version.

**Comment by erickzanardo** [comment]
We just published 0.10.4 yo address this, could you test please?

**Comment by erickzanardo** [comment]
Did you get to test the fix on `0.10.4` @oth-aw ?

**Comment by oth-aw** [comment]
Hi, sorry for the late answer. Yes it works! Thanks!
