### ISSUE TITLE
Issue with "flutter_svg" dependency

### ISSUE THREAD

**Issue by gabrielpacheco23** [luanpotter/flame#91]
I've tried to run a Flame project on Linux, but it didn't work with the latest version. It seems to be an issue with `flutter_svg` dependency.

**Comment by erickzanardo** [comment]
@gabrielpacheco23 desktop support is on our plans, but right we do not offer support for it, mainly because flutter desktop is in its very early stages, and they already warned that breaking changes will happen. So we are waiting, at least a little while to offer support to it, we may start support this, when the desktop support land on flutter dev channel.

In the mean time, since you have already identified that flutter_svg has some problems working on desktop, I would suggest opening an issue on their github: https://github.com/dnfield/flutter_svg

Thanks.
